### ISSUE TITLE
Добавить авторизацию через куки

### ISSUE THREAD

**Issue by Uristrix** [Uristrix/Automata#8]
Библа уже прикручена, сделай, чтоб при инициализации страницы обновлялся стор. (тупо пароль, логин из кук и инфа о челе)
P.S. посмотри в auth шаблончик.

**Comment by Depthmane** [comment]
![печатает боб](https://user-images.githubusercontent.com/117308187/236645207-38034dcb-dbfa-4b75-aa20-760d594ac8d9.gif)
